// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJaB-e7F5HHmHWVCLN2w7etKXKPRuUTYs',
    appId: '1:338936417668:web:13f18dfb90992c4ba1a1d1',
    messagingSenderId: '338936417668',
    projectId: 'eestech-final',
    authDomain: 'eestech-final.firebaseapp.com',
    storageBucket: 'eestech-final.appspot.com',
    measurementId: 'G-BT8HDX5MDN',
    databaseURL: "https://eestech-final.firebaseio.com",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY4-7S3X95-rYhsIeLaMDoqRtYtZx8-QI',
    appId: '1:338936417668:android:bc043a75c6ab52c0a1a1d1',
    messagingSenderId: '338936417668',
    projectId: 'eestech-final',
    storageBucket: 'eestech-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjRO-MRuvD_5gAlhW7RbBX8cj1mNz9lG0',
    appId: '1:338936417668:ios:e79476cf48ea4635a1a1d1',
    messagingSenderId: '338936417668',
    projectId: 'eestech-final',
    storageBucket: 'eestech-final.appspot.com',
    iosClientId: '338936417668-k5i64mfl7m3b8s0e2lbqcinltul9o72g.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjRO-MRuvD_5gAlhW7RbBX8cj1mNz9lG0',
    appId: '1:338936417668:ios:e79476cf48ea4635a1a1d1',
    messagingSenderId: '338936417668',
    projectId: 'eestech-final',
    storageBucket: 'eestech-final.appspot.com',
    iosClientId: '338936417668-k5i64mfl7m3b8s0e2lbqcinltul9o72g.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );
}
